// examples/vue/src/components/Navbar.vue
//src/components/Navbar.vue
<template>
  <div>
    <b-navbar toggleable="lg" type="dark" variant="success">
      <b-container>
          <b-navbar-brand href="#">Application</b-navbar-brand>
          <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>
          <b-collapse id="nav-collapse" is-nav>
            <!-- Right aligned nav items -->
            <b-navbar-nav class="ml-auto">
              
              <b-nav-item-dropdown right>
                <!-- Using 'button-content' slot -->
                <template slot="button-content"><em>Nothing here yet</em></template>
                <b-dropdown-item href="#">Some Action</b-dropdown-item>
                
              </b-nav-item-dropdown>
            </b-navbar-nav>
          </b-collapse>
        </b-container>
    </b-navbar>
  </div>  
</template>

// examples/svelte/src/components/Navbar.svelte
<div>
  <nav class="navbar navbar-expand-lg navbar-dark bg-success ">
    <div class="container">
        <a class="navbar-brand" href={"#"} >Application</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <!-- 
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
            -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href={"#"} id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <em>Nothing here yet</em>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href={"#"} >Some Action</a>
              </div>
            </li>
          </ul>
      </div>
    </div>
  </nav>
</div>
