// examples/svelte/src/components/Sample.svelte
<script>
  import backend from "nimview"
  // backend.init().then(() => console.log("ready"))
  let search = ""
  let elements = []
  let runSearch = () => {
    elements = elements.concat({text: search})
    backend.appendSomething(search).then(response => {
      // console.log(response)
      search = response
    })
  }
</script>
<div class="container sample">
  <li class="form-inline">
    <form class="form-inline" on:submit|preventDefault={runSearch}>
      <input class="form-control mr-sm-2" type="search" placeholder="Search for ..." aria-label="search" bind:value={search}>
      <button type="button" on:click={runSearch} class="btn btn-success my-2 my-sm-0">Search</button>
    </form>
  </li>
  <div>
    {#if ((typeof elements !== "undefined") && (elements.length > 0))}
      {#each elements as el}
      <div>
        {el.text}
      </div>
      {/each}
    {:else}
    <p>No data available yet</p>
    {/if}
  </div>
</div>

<style>
.sample {
  margin-top: 5px;
}
</style>

// ui/src/components/Sample.vue
//src/components/Sample.vue
<template>
  <b-container>
  <b-nav-form>
    <b-form-input 
      size="sm" 
      class="mr-sm-2" 
      placeholder="Search for..."
      v-model="search"
      ></b-form-input>
    <b-button 
      size="sm" 
      class="my-2 my-sm-0" 
      type="submit" 
      @click.prevent="runSearch"
      >Search</b-button>
  </b-nav-form>
    <div v-if="elements.length">
      <b-row>
        <div v-bind:key="data.index" v-for="data in elements">
          <b-col l="4">
            <b-card
              v-bind:title="data.strCategory"
              v-bind:img-src="data.strCategoryThumb"
              img-alt="Image"
              img-top
              tag="article"
              style="max-width: 20rem;"
              class="mb-2">
              <b-card-text>{{ `${data.strCategoryDescription.slice(0,100)}...` }}</b-card-text>
              <b-button href="#" variant="primary">View data</b-button>
            </b-card>
          </b-col>
        </div>
      </b-row>
    </div>
    <div v-else>
      <h5>No data available yet ??</h5>
    </div>
  </b-container>
</template>

<script>
export default {
  data() {
    return {
      elements: [],
      search: ''
    };
  },
  methods: {
    runSearch() {
      this.nimCall("appendSomething", this, 'search')
    }
  },/* 
// import axios from "axios";
  mounted() {
    axios
      .get("https://www.themealdb.com/api/json/v1/1/categories.php")
      .then(response => {
        this.search = response.data.categories;
      })
      .catch(err => {
        console.log(err);
      });
      
  }*/
};
</script>
